### ISSUE TITLE
Error of running `train_flux_lora_deepspeed.py`

### ISSUE THREAD

**Issue by HelloWarcraft** [XLabs-AI/x-flux#44]
Does anyone run `accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"` successfully？

My 80G VRAM encounted a `CUDA out of memory` when I trained 1024pxl-image dataset. 

So I tried to use `train_flux_lora_deepspeed.py`：

> ```yaml
> compute_environment: LOCAL_MACHINE
> debug: false                                                                                               
> deepspeed_config:
>   gradient_accumulation_steps: 2
>   gradient_clipping: 1.0
>   offload_optimizer_device: none
>   offload_param_device: none
>   zero3_init_flag: false
>   zero_stage: 2
> distributed_type: DEEPSPEED
> downcast_bf16: 'no'
> enable_cpu_affinity: false
> machine_rank: 0
> main_training_function: main
> mixed_precision: bf16
> num_machines: 1
> num_processes: 1
> rdzv_backend: static
> same_network: true
> tpu_env: []
> tpu_use_cluster: false
> tpu_use_sudo: false
> use_cpu: false
> ```

I saved the above code to `~/x-flux/accelerate_config.yaml`, and run `cd ~/x-flux && accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"`

Then I got a long Error report:
```shell
[2024-08-13 13:16:00,273] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0813 13:16:15.667000 139664608732352 torch/distributed/run.py:757] 
W0813 13:16:15.667000 139664608732352 torch/distributed/run.py:757] *****************************************
W0813 13:16:15.667000 139664608732352 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0813 13:16:15.667000 139664608732352 torch/distributed/run.py:757] *****************************************
[2024-08-13 13:16:46,154] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,155] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,155] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,156] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,156] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,192] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,239] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:46,300] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-13 13:16:48,144] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,145] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,145] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,145] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,145] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,148] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,148] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 13:16:48,148] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-08-13 13:16:48,148] [INFO] [comm.py:637:init_distributed] cdb=None
[rank7]: Traceback (most recent call last):
[rank7]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank7]:     main()
[rank7]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank7]:     accelerator = Accelerator(
[rank7]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank7]:     self.state = AcceleratorState(
[rank7]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank7]:     PartialState(cpu, **kwargs)
[rank7]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank7]:     self.set_device()
[rank7]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank7]:     torch.cuda.set_device(self.device)
[rank7]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank7]:     torch._C._cuda_setDevice(device)
[rank7]: RuntimeError: CUDA error: invalid device ordinal
[rank7]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank7]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank7]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank4]: Traceback (most recent call last):
[rank4]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank4]:     main()
[rank4]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank4]:     accelerator = Accelerator(
[rank4]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank4]:     self.state = AcceleratorState(
[rank4]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank4]:     PartialState(cpu, **kwargs)
[rank4]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank4]:     self.set_device()
[rank4]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank4]:     torch.cuda.set_device(self.device)
[rank4]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank4]:     torch._C._cuda_setDevice(device)
[rank4]: RuntimeError: CUDA error: invalid device ordinal
[rank4]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank4]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank4]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank2]: Traceback (most recent call last):
[rank2]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank2]:     main()
[rank2]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank2]:     accelerator = Accelerator(
[rank2]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank2]:     self.state = AcceleratorState(
[rank2]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank2]:     PartialState(cpu, **kwargs)
[rank2]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank2]:     self.set_device()
[rank2]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank2]:     torch.cuda.set_device(self.device)
[rank2]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank2]:     torch._C._cuda_setDevice(device)
[rank2]: RuntimeError: CUDA error: invalid device ordinal
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank6]: Traceback (most recent call last):
[rank6]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank6]:     main()
[rank6]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank6]:     accelerator = Accelerator(
[rank6]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank6]:     self.state = AcceleratorState(
[rank6]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank6]:     PartialState(cpu, **kwargs)
[rank6]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank6]:     self.set_device()
[rank6]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank6]:     torch.cuda.set_device(self.device)
[rank6]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank6]:     torch._C._cuda_setDevice(device)
[rank6]: RuntimeError: CUDA error: invalid device ordinal
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank3]: Traceback (most recent call last):
[rank3]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank3]:     main()
[rank3]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank3]:     accelerator = Accelerator(
[rank3]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank3]:     self.state = AcceleratorState(
[rank3]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank3]:     PartialState(cpu, **kwargs)
[rank3]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank3]:     self.set_device()
[rank3]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank3]:     torch.cuda.set_device(self.device)
[rank3]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank3]:     torch._C._cuda_setDevice(device)
[rank3]: RuntimeError: CUDA error: invalid device ordinal
[rank3]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank3]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank3]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank1]:     main()
[rank1]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank1]:     accelerator = Accelerator(
[rank1]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank1]:     self.state = AcceleratorState(
[rank1]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank1]:     PartialState(cpu, **kwargs)
[rank1]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank1]:     self.set_device()
[rank1]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank1]:     torch.cuda.set_device(self.device)
[rank1]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank1]:     torch._C._cuda_setDevice(device)
[rank1]: RuntimeError: CUDA error: invalid device ordinal
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank5]: Traceback (most recent call last):
[rank5]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 301, in <module>
[rank5]:     main()
[rank5]:   File "/root/flux_train/x-flux/train_flux_lora_deepspeed.py", line 76, in main
[rank5]:     accelerator = Accelerator(
[rank5]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py", line 378, in __init__
[rank5]:     self.state = AcceleratorState(
[rank5]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 853, in __init__
[rank5]:     PartialState(cpu, **kwargs)
[rank5]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 281, in __init__
[rank5]:     self.set_device()
[rank5]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/state.py", line 793, in set_device
[rank5]:     torch.cuda.set_device(self.device)
[rank5]:   File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank5]:     torch._C._cuda_setDevice(device)
[rank5]: RuntimeError: CUDA error: invalid device ordinal
[rank5]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank5]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank5]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py:401: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
08/13/2024 13:16:48 - INFO - __main__ - Distributed environment: DEEPSPEED  Backend: nccl
Num processes: 8
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: fp16
ds_config: {'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 'auto', 'gradient_accumulation_steps': 1, 'zero_optimization': {'stage': 2, 'offload_optimizer': {'device': 'cpu', 'nvme_path': None}, 'offload_param': {'device': 'cpu', 'nvme_path': None}, 'stage3_gather_16bit_weights_on_model_save': False}, 'gradient_clipping': 1.0, 'steps_per_print': inf, 'fp16': {'enabled': True, 'auto_cast': True}, 'bf16': {'enabled': False}}

/root/.conda/envs/x-flux/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
W0813 13:16:55.806000 139664608732352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 17078 closing signal SIGTERM
E0813 13:16:56.020000 139664608732352 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 17079) of binary: /root/.conda/envs/x-flux/bin/python
Traceback (most recent call last):
  File "/root/.conda/envs/x-flux/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1067, in launch_command
    deepspeed_launcher(args)
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 771, in deepspeed_launcher
    distrib_run.run(args)
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/.conda/envs/x-flux/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_flux_lora_deepspeed.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 17080)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 17081)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 17082)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 17083)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 17084)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 17085)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-13_13:16:55
  host      : intern-studio-5003463
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 17079)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

and the packages in my `x-flux` conda environment is：
```shell
Package                  Version
------------------------ -----------
accelerate               0.30.1
aiohappyeyeballs         2.3.5
aiohttp                  3.10.2
aiosignal                1.3.1
annotated-types          0.7.0
antlr4-python3-runtime   4.9.3
async-timeout            4.0.3
attrs                    24.2.0
certifi                  2024.7.4
charset-normalizer       3.3.2
cmake                    3.30.2
coloredlogs              15.0.1
datasets                 2.20.0
deepspeed                0.13.0
diffusers                0.30.0
dill                     0.3.8
einops                   0.8.0
filelock                 3.15.4
frozenlist               1.4.1
fsspec                   2024.5.0
hjson                    3.1.0
huggingface-hub          0.24.5
humanfriendly            10.0
idna                     3.7
importlib_metadata       8.2.0
Jinja2                   3.1.4
lit                      18.1.8
MarkupSafe               2.1.5
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.3
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-ml-py             12.555.43
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
optimum-quanto           0.2.1
packaging                24.1
pandas                   2.2.2
pillow                   10.4.0
pip                      24.0
protobuf                 5.27.3
psutil                   6.0.0
py-cpuinfo               9.0.0
pyarrow                  17.0.0
pyarrow-hotfix           0.6
pydantic                 2.8.2
pydantic_core            2.20.1
pynvml                   11.5.3
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
safetensors              0.4.4
sentencepiece            0.2.0
setuptools               72.1.0
six                      1.16.0
sympy                    1.13.1
tokenizers               0.15.2
torch                    2.3.0
tqdm                     4.66.5
transformers             4.39.3
triton                   2.3.0
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
wheel                    0.43.0
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.19.2
```

**Comment by HelloWarcraft** [comment]
problem solved when I use A100 * 2..., before this I also changed some version of package:
```shell
pip install torch==2.4.0+cu121 torchvision==0.19.0+cu121 torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
pip install deepspeed==0.14.4 transformers==4.43.3 optimum-quanto==0.2.4
```
```shell
# accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"
[2024-08-13 15:12:35,306] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The default cache directory for DeepSpeed Triton autotune, /root/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
 [WARNING]  using untested triton version (3.0.0), only 1.0.0 is known to be compatible
/root/.conda/envs/x-flux/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/root/.conda/envs/x-flux/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
[2024-08-13 15:12:56,580] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The default cache directory for DeepSpeed Triton autotune, /root/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
 [WARNING]  using untested triton version (3.0.0), only 1.0.0 is known to be compatible
/root/.conda/envs/x-flux/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/root/.conda/envs/x-flux/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
[2024-08-13 15:12:58,212] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-13 15:12:58,212] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
/root/.conda/envs/x-flux/lib/python3.10/site-packages/accelerate/accelerator.py:401: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
08/13/2024 15:12:58 - INFO - __main__ - Distributed environment: DEEPSPEED  Backend: nccl
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: bf16
ds_config: {'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 'auto', 'gradient_accumulation_steps': 2, 'zero_optimization': {'stage': 2, 'offload_optimizer': {'device': 'none', 'nvme_path': None}, 'offload_param': {'device': 'none', 'nvme_path': None}, 'stage3_gather_16bit_weights_on_model_save': False}, 'gradient_clipping': 1.0, 'steps_per_print': inf, 'bf16': {'enabled': True}, 'fp16': {'enabled': False}}

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Init model
Loading checkpoint
Init AE
double_blocks.0.processor.qkv_lora1.down.weight
double_blocks.0.processor.qkv_lora1.up.weight
double_blocks.0.processor.proj_lora1.down.weight
double_blocks.0.processor.proj_lora1.up.weight
double_blocks.0.processor.qkv_lora2.down.weight
double_blocks.0.processor.qkv_lora2.up.weight
double_blocks.0.processor.proj_lora2.down.weight
double_blocks.0.processor.proj_lora2.up.weight
double_blocks.1.processor.qkv_lora1.down.weight
double_blocks.1.processor.qkv_lora1.up.weight
double_blocks.1.processor.proj_lora1.down.weight
double_blocks.1.processor.proj_lora1.up.weight
double_blocks.1.processor.qkv_lora2.down.weight
double_blocks.1.processor.qkv_lora2.up.weight
double_blocks.1.processor.proj_lora2.down.weight
double_blocks.1.processor.proj_lora2.up.weight
double_blocks.2.processor.qkv_lora1.down.weight
double_blocks.2.processor.qkv_lora1.up.weight
double_blocks.2.processor.proj_lora1.down.weight
double_blocks.2.processor.proj_lora1.up.weight
double_blocks.2.processor.qkv_lora2.down.weight
double_blocks.2.processor.qkv_lora2.up.weight
double_blocks.2.processor.proj_lora2.down.weight
double_blocks.2.processor.proj_lora2.up.weight
double_blocks.3.processor.qkv_lora1.down.weight
double_blocks.3.processor.qkv_lora1.up.weight
double_blocks.3.processor.proj_lora1.down.weight
double_blocks.3.processor.proj_lora1.up.weight
double_blocks.3.processor.qkv_lora2.down.weight
double_blocks.3.processor.qkv_lora2.up.weight
double_blocks.3.processor.proj_lora2.down.weight
double_blocks.3.processor.proj_lora2.up.weight
double_blocks.4.processor.qkv_lora1.down.weight
double_blocks.4.processor.qkv_lora1.up.weight
double_blocks.4.processor.proj_lora1.down.weight
double_blocks.4.processor.proj_lora1.up.weight
double_blocks.4.processor.qkv_lora2.down.weight
double_blocks.4.processor.qkv_lora2.up.weight
double_blocks.4.processor.proj_lora2.down.weight
double_blocks.4.processor.proj_lora2.up.weight
double_blocks.5.processor.qkv_lora1.down.weight
double_blocks.5.processor.qkv_lora1.up.weight
double_blocks.5.processor.proj_lora1.down.weight
double_blocks.5.processor.proj_lora1.up.weight
double_blocks.5.processor.qkv_lora2.down.weight
double_blocks.5.processor.qkv_lora2.up.weight
double_blocks.5.processor.proj_lora2.down.weight
double_blocks.5.processor.proj_lora2.up.weight
double_blocks.6.processor.qkv_lora1.down.weight
double_blocks.6.processor.qkv_lora1.up.weight
double_blocks.6.processor.proj_lora1.down.weight
double_blocks.6.processor.proj_lora1.up.weight
double_blocks.6.processor.qkv_lora2.down.weight
double_blocks.6.processor.qkv_lora2.up.weight
double_blocks.6.processor.proj_lora2.down.weight
double_blocks.6.processor.proj_lora2.up.weight
double_blocks.7.processor.qkv_lora1.down.weight
double_blocks.7.processor.qkv_lora1.up.weight
double_blocks.7.processor.proj_lora1.down.weight
double_blocks.7.processor.proj_lora1.up.weight
double_blocks.7.processor.qkv_lora2.down.weight
double_blocks.7.processor.qkv_lora2.up.weight
double_blocks.7.processor.proj_lora2.down.weight
double_blocks.7.processor.proj_lora2.up.weight
double_blocks.8.processor.qkv_lora1.down.weight
double_blocks.8.processor.qkv_lora1.up.weight
double_blocks.8.processor.proj_lora1.down.weight
double_blocks.8.processor.proj_lora1.up.weight
double_blocks.8.processor.qkv_lora2.down.weight
double_blocks.8.processor.qkv_lora2.up.weight
double_blocks.8.processor.proj_lora2.down.weight
double_blocks.8.processor.proj_lora2.up.weight
double_blocks.9.processor.qkv_lora1.down.weight
double_blocks.9.processor.qkv_lora1.up.weight
double_blocks.9.processor.proj_lora1.down.weight
double_blocks.9.processor.proj_lora1.up.weight
double_blocks.9.processor.qkv_lora2.down.weight
double_blocks.9.processor.qkv_lora2.up.weight
double_blocks.9.processor.proj_lora2.down.weight
double_blocks.9.processor.proj_lora2.up.weight
double_blocks.10.processor.qkv_lora1.down.weight
double_blocks.10.processor.qkv_lora1.up.weight
double_blocks.10.processor.proj_lora1.down.weight
double_blocks.10.processor.proj_lora1.up.weight
double_blocks.10.processor.qkv_lora2.down.weight
double_blocks.10.processor.qkv_lora2.up.weight
double_blocks.10.processor.proj_lora2.down.weight
double_blocks.10.processor.proj_lora2.up.weight
double_blocks.11.processor.qkv_lora1.down.weight
double_blocks.11.processor.qkv_lora1.up.weight
double_blocks.11.processor.proj_lora1.down.weight
double_blocks.11.processor.proj_lora1.up.weight
double_blocks.11.processor.qkv_lora2.down.weight
double_blocks.11.processor.qkv_lora2.up.weight
double_blocks.11.processor.proj_lora2.down.weight
double_blocks.11.processor.proj_lora2.up.weight
double_blocks.12.processor.qkv_lora1.down.weight
double_blocks.12.processor.qkv_lora1.up.weight
double_blocks.12.processor.proj_lora1.down.weight
double_blocks.12.processor.proj_lora1.up.weight
double_blocks.12.processor.qkv_lora2.down.weight
double_blocks.12.processor.qkv_lora2.up.weight
double_blocks.12.processor.proj_lora2.down.weight
double_blocks.12.processor.proj_lora2.up.weight
double_blocks.13.processor.qkv_lora1.down.weight
double_blocks.13.processor.qkv_lora1.up.weight
double_blocks.13.processor.proj_lora1.down.weight
double_blocks.13.processor.proj_lora1.up.weight
double_blocks.13.processor.qkv_lora2.down.weight
double_blocks.13.processor.qkv_lora2.up.weight
double_blocks.13.processor.proj_lora2.down.weight
double_blocks.13.processor.proj_lora2.up.weight
double_blocks.14.processor.qkv_lora1.down.weight
double_blocks.14.processor.qkv_lora1.up.weight
double_blocks.14.processor.proj_lora1.down.weight
double_blocks.14.processor.proj_lora1.up.weight
double_blocks.14.processor.qkv_lora2.down.weight
double_blocks.14.processor.qkv_lora2.up.weight
double_blocks.14.processor.proj_lora2.down.weight
double_blocks.14.processor.proj_lora2.up.weight
double_blocks.15.processor.qkv_lora1.down.weight
double_blocks.15.processor.qkv_lora1.up.weight
double_blocks.15.processor.proj_lora1.down.weight
double_blocks.15.processor.proj_lora1.up.weight
double_blocks.15.processor.qkv_lora2.down.weight
double_blocks.15.processor.qkv_lora2.up.weight
double_blocks.15.processor.proj_lora2.down.weight
double_blocks.15.processor.proj_lora2.up.weight
double_blocks.16.processor.qkv_lora1.down.weight
double_blocks.16.processor.qkv_lora1.up.weight
double_blocks.16.processor.proj_lora1.down.weight
double_blocks.16.processor.proj_lora1.up.weight
double_blocks.16.processor.qkv_lora2.down.weight
double_blocks.16.processor.qkv_lora2.up.weight
double_blocks.16.processor.proj_lora2.down.weight
double_blocks.16.processor.proj_lora2.up.weight
double_blocks.17.processor.qkv_lora1.down.weight
double_blocks.17.processor.qkv_lora1.up.weight
double_blocks.17.processor.proj_lora1.down.weight
double_blocks.17.processor.proj_lora1.up.weight
double_blocks.17.processor.qkv_lora2.down.weight
double_blocks.17.processor.qkv_lora2.up.weight
double_blocks.17.processor.proj_lora2.down.weight
double_blocks.17.processor.proj_lora2.up.weight
double_blocks.18.processor.qkv_lora1.down.weight
double_blocks.18.processor.qkv_lora1.up.weight
double_blocks.18.processor.proj_lora1.down.weight
double_blocks.18.processor.proj_lora1.up.weight
double_blocks.18.processor.qkv_lora2.down.weight
double_blocks.18.processor.qkv_lora2.up.weight
double_blocks.18.processor.proj_lora2.down.weight
double_blocks.18.processor.proj_lora2.up.weight
11.206656 parameters
[2024-08-13 15:13:28,173] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.14.4, git-hash=unknown, git-branch=unknown
[2024-08-13 15:13:37,680] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2024-08-13 15:13:37,682] [INFO] [logging.py:96:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2024-08-13 15:13:37,682] [INFO] [logging.py:96:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2024-08-13 15:13:37,693] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2024-08-13 15:13:37,693] [INFO] [utils.py:56:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'torch.optim.adamw.AdamW'>
[2024-08-13 15:13:37,693] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.bfloat16 ZeRO stage 2 optimizer
[2024-08-13 15:13:37,693] [INFO] [stage_1_and_2.py:148:__init__] Reduce bucket size 500,000,000
[2024-08-13 15:13:37,693] [INFO] [stage_1_and_2.py:149:__init__] Allgather bucket size 500,000,000
[2024-08-13 15:13:37,693] [INFO] [stage_1_and_2.py:150:__init__] CPU Offload: False
[2024-08-13 15:13:37,693] [INFO] [stage_1_and_2.py:151:__init__] Round robin gradient partitioning: False
[2024-08-13 15:13:37,892] [INFO] [utils.py:781:see_memory_usage] Before initializing optimizer states
[2024-08-13 15:13:37,892] [INFO] [utils.py:782:see_memory_usage] MA 31.65 GB         Max_MA 31.67 GB         CA 31.74 GB         Max_CA 32 GB 
[2024-08-13 15:13:37,892] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 76.66 GB, percent = 3.8%
[2024-08-13 15:13:38,021] [INFO] [utils.py:781:see_memory_usage] After initializing optimizer states
[2024-08-13 15:13:38,022] [INFO] [utils.py:782:see_memory_usage] MA 31.65 GB         Max_MA 31.7 GB         CA 31.78 GB         Max_CA 32 GB 
[2024-08-13 15:13:38,022] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 76.67 GB, percent = 3.8%
[2024-08-13 15:13:38,022] [INFO] [stage_1_and_2.py:543:__init__] optimizer state initialized
[2024-08-13 15:13:38,146] [INFO] [utils.py:781:see_memory_usage] After initializing ZeRO optimizer
[2024-08-13 15:13:38,147] [INFO] [utils.py:782:see_memory_usage] MA 31.65 GB         Max_MA 31.65 GB         CA 31.78 GB         Max_CA 32 GB 
[2024-08-13 15:13:38,147] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 76.66 GB, percent = 3.8%
[2024-08-13 15:13:38,149] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Final Optimizer = DeepSpeedZeroOptimizer
[2024-08-13 15:13:38,149] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed using client LR scheduler
[2024-08-13 15:13:38,149] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2024-08-13 15:13:38,149] [INFO] [logging.py:96:log_dist] [Rank 0] step=0, skipped=0, lr=[0.0001], mom=[(0.9, 0.999)]
[2024-08-13 15:13:38,151] [INFO] [config.py:997:print] DeepSpeedEngine configuration:
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   activation_checkpointing_config  {
    "partition_activations": false, 
    "contiguous_memory_optimization": false, 
    "cpu_checkpointing": false, 
    "number_checkpoints": null, 
    "synchronize_checkpoint_boundary": false, 
    "profile": false
}
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   amp_enabled .................. False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   amp_params ................... False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   autotuning_config ............ {
    "enabled": false, 
    "start_step": null, 
    "end_step": null, 
    "metric_path": null, 
    "arg_mappings": null, 
    "metric": "throughput", 
    "model_info": null, 
    "results_dir": "autotuning_results", 
    "exps_dir": "autotuning_exps", 
    "overwrite": true, 
    "fast": true, 
    "start_profile_step": 3, 
    "end_profile_step": 5, 
    "tuner_type": "gridsearch", 
    "tuner_early_stopping": 5, 
    "tuner_num_trials": 50, 
    "model_info_path": null, 
    "mp_size": 1, 
    "max_train_batch_size": null, 
    "min_train_batch_size": 1, 
    "max_train_micro_batch_size_per_gpu": 1.024000e+03, 
    "min_train_micro_batch_size_per_gpu": 1, 
    "num_tuning_micro_batch_sizes": 3
}
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   bfloat16_enabled ............. True
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   bfloat16_immediate_grad_update  False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   checkpoint_parallel_write_pipeline  False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   checkpoint_tag_validation_enabled  True
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   checkpoint_tag_validation_fail  False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7fe4d27ce110>
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   communication_data_type ...... None
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   curriculum_enabled_legacy .... False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   curriculum_params_legacy ..... False
[2024-08-13 15:13:38,151] [INFO] [config.py:1001:print]   data_efficiency_config ....... {'enabled': False, 'seed': 1234, 'data_sampling': {'enabled': False, 'num_epochs': 1000, 'num_workers': 0, 'curriculum_learning': {'enabled': False}}, 'data_routing': {'enabled': False, 'random_ltd': {'enabled': False, 'layer_token_lr_schedule': {'enabled': False}}}}
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   data_efficiency_enabled ...... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   dataloader_drop_last ......... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   disable_allgather ............ False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   dump_state ................... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   dynamic_loss_scale_args ...... None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_enabled ........... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_gas_boundary_resolution  1
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_layer_num ......... 0
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_max_iter .......... 100
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_stability ......... 1e-06
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_tol ............... 0.01
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   eigenvalue_verbose ........... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   elasticity_enabled ........... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   flops_profiler_config ........ {
    "enabled": false, 
    "recompute_fwd_factor": 0.0, 
    "profile_step": 1, 
    "module_depth": -1, 
    "top_modules": 1, 
    "detailed": true, 
    "output_file": null
}
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   fp16_auto_cast ............... None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   fp16_enabled ................. False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   fp16_master_weights_and_gradients  False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   global_rank .................. 0
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   grad_accum_dtype ............. None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   gradient_accumulation_steps .. 2
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   gradient_clipping ............ 1.0
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   gradient_predivide_factor .... 1.0
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   graph_harvesting ............. False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   hybrid_engine ................ enabled=False max_out_tokens=512 inference_tp_size=1 release_inference_cache=False pin_parameters=True tp_gather_partition_size=8
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   initial_dynamic_scale ........ 1
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   load_universal_checkpoint .... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   loss_scale ................... 1.0
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   memory_breakdown ............. False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   mics_hierarchial_params_gather  False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   mics_shard_size .............. -1
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   monitor_config ............... tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') comet=CometConfig(enabled=False, samples_log_interval=100, project=None, workspace=None, api_key=None, experiment_name=None, experiment_key=None, online=None, mode=None) wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed') csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') enabled=False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   nebula_config ................ {
    "enabled": false, 
    "persistent_storage_path": null, 
    "persistent_time_interval": 100, 
    "num_of_version_in_retention": 2, 
    "enable_nebula_load": true, 
    "load_path": null
}
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   optimizer_legacy_fusion ...... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   optimizer_name ............... None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   optimizer_params ............. None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0, 'pipe_partitioned': True, 'grad_partitioned': True}
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   pld_enabled .................. False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   pld_params ................... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   prescale_gradients ........... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   scheduler_name ............... None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   scheduler_params ............. None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   seq_parallel_communication_data_type  torch.float32
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   sparse_attention ............. None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   sparse_gradients_enabled ..... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   steps_per_print .............. inf
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   timers_config ................ enabled=True synchronized=True
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   train_batch_size ............. 2
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   train_micro_batch_size_per_gpu  1
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   use_data_before_expert_parallel_  False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   use_node_local_storage ....... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   wall_clock_breakdown ......... False
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   weight_quantization_config ... None
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   world_size ................... 1
[2024-08-13 15:13:38,152] [INFO] [config.py:1001:print]   zero_allow_untested_optimizer  True
[2024-08-13 15:13:38,153] [INFO] [config.py:1001:print]   zero_config .................. stage=2 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500,000,000 use_multi_rank_bucket_allreduce=True allgather_partitions=True allgather_bucket_size=500,000,000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=DeepSpeedZeroOffloadParamConfig(device='none', nvme_path=None, buffer_count=5, buffer_size=100,000,000, max_in_cpu=1,000,000,000, pin_memory=False) offload_optimizer=DeepSpeedZeroOffloadOptimizerConfig(device='none', nvme_path=None, buffer_count=4, pin_memory=False, pipeline=False, pipeline_read=False, pipeline_write=False, fast_init=False, ratio=1.0) sub_group_size=1,000,000,000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50,000,000 param_persistence_threshold=100,000 model_persistence_threshold=sys.maxsize max_live_parameters=1,000,000,000 max_reuse_distance=1,000,000,000 gather_16bit_weights_on_model_save=False use_all_reduce_for_fetch_params=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False zero_hpz_partition_size=1 zero_quantized_weights=False zero_quantized_nontrainable_weights=False zero_quantized_gradients=False mics_shard_size=-1 mics_hierarchical_params_gather=False memory_efficient_linear=True pipeline_loading_checkpoint=False override_module_apply=True
[2024-08-13 15:13:38,153] [INFO] [config.py:1001:print]   zero_enabled ................. True
[2024-08-13 15:13:38,153] [INFO] [config.py:1001:print]   zero_force_ds_cpu_optimizer .. True
[2024-08-13 15:13:38,153] [INFO] [config.py:1001:print]   zero_optimization_stage ...... 2
[2024-08-13 15:13:38,153] [INFO] [config.py:987:print_user_config]   json = {
    "train_batch_size": 2, 
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 2, 
    "zero_optimization": {
        "stage": 2, 
        "offload_optimizer": {
            "device": "none", 
            "nvme_path": null
        }, 
        "offload_param": {
            "device": "none", 
            "nvme_path": null
        }, 
        "stage3_gather_16bit_weights_on_model_save": false
    }, 
    "gradient_clipping": 1.0, 
    "steps_per_print": inf, 
    "bf16": {
        "enabled": true
    }, 
    "fp16": {
        "enabled": false
    }, 
    "zero_allow_untested_optimizer": true
}
08/13/2024 15:13:38 - INFO - __main__ - ***** Running training *****
08/13/2024 15:13:38 - INFO - __main__ -   Num Epochs = 417
08/13/2024 15:13:38 - INFO - __main__ -   Instantaneous batch size per device = 1
08/13/2024 15:13:38 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
08/13/2024 15:13:38 - INFO - __main__ -   Gradient Accumulation steps = 1
08/13/2024 15:13:38 - INFO - __main__ -   Total optimization steps = 10000
Steps:   0%|▍                                                                                                 | 48/10000 [00:47<2:32:13,  1.09it/s, lr=0.0001, step_loss=0.475]
```
The train starts, and the VRAM cost is 42G：
```
Tue Aug 13 15:16:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:13:00.0 Off |                    0 |
| N/A   51C    P0             366W / 400W |  42837MiB / 81920MiB |     97%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  | 00000000:AD:00.0 Off |                    0 |
| N/A   26C    P0              63W / 400W |      7MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```
I don't know why the codes run normally when I turn switch to A100 * 2 tier in jupyter-lab environment.
lol, it costs a lot of money...

**Comment by HelloWarcraft** [comment]
I see, set larger batch size, and train with shorter time.

**Comment by vincezh2000** [comment]
Trying config accelerate. You may missed this step otherwise itll cost much more vram

**Comment by HelloWarcraft** [comment]
> accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"

I runned `accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"`.

I think this command includes "config accelerate" since ` --config_file "accelerate_config.yaml"` is one argument after `accelerate launch`

When I tunrn on A100 40G GPU tier in jupyter-lab, and train by that  command, it reported errors and stopped training.

When changed the tier to A100 80G *2, this command runs and the train works well, using 40G VRAM. It cost a lot, but I still used it since it works well in training. Maybe I have to wait for the update of x-flux or some other new training scripts.

**Comment by vincezh2000** [comment]
> > accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"
> 
> I runned `accelerate launch --config_file "accelerate_config.yaml" train_flux_lora_deepspeed.py --config "train_configs/test_lora.yaml"`.
> 
> I think this command includes "config accelerate" since ` --config_file "accelerate_config.yaml"` is one argument after `accelerate launch`
> 
> When I turned on A100 40G GPU tier in jupyter-lab, and trained by that command, it reported errors and stopped training.
> 
> When I change the tier to A100 80G *2, this command runs and the train works well, using 40G VRAM. It costs a lot, but I still use it since it works well in training. Maybe I have to wait for the update of x-flux or some other new training scripts.

Yea, that's the reason you are using 40gb version rather than 80gb. It costs above 40 gb vram while training lora.

**Comment by kadirnar** [comment]
@HelloWarcraft 

I want to train Controlnet model with multi-gpu. But multi-gpu is not working. Can you help me? How should I set the config settings?

**Comment by chenbinghui1** [comment]
@kadirnar  have you solved this problem?

> @HelloWarcraft
> 
> I want to train Controlnet model with multi-gpu. But multi-gpu is not working. Can you help me? How should I set the config settings?

I use the same command for another my own script, it can train on multiple-gpus, but when changed to train_flux_deepspeed_controlnet.py script, it failed.

**Comment by Lotayou** [comment]
I see this repo does not contain xformer memory-efficient attention support yet (until 20240910), both dit and ae simply inherits torch.nn.Module instead of diffusers pipeline. A manual switch of all attention operators could be beneficial for training lora on ~40Gb GPUs (A10040G, L40s, etc)

@x-labs-ai any future plans in supporting xformers for reducing memory consumption?
